import { makeStyles } from "@material-ui/styles";
import Images from "~/assets/js/images.js";

export const useStyles = makeStyles({
    root_bottom:{
        position:'absolute',
        top:'100%',
        left:'50%',
        transform:'translateX(-50%)',
        marginTop:'-1px',
        "&:before" :{
            content: `''`,
            width: '12px',
            height: '30px',
            borderStyle: 'solid',
            borderWidth: '15px 6px 15px 6px',
            boxSizing: 'border-box',
            borderColor: '#000 transparent transparent transparent',
            position: 'absolute',
            left: '50%',
            top: '0px',
            transform: 'translateX(-50%)',
        },
        "&:after" :{
            content: `''`,
            width: '12px',
            height: '30px',
            borderStyle: 'solid',
            borderWidth: '15px 6px 15px 6px',
            boxSizing: 'border-box',
            borderColor: '#fff transparent transparent transparent',
            position: 'absolute',
            left: '50%',
            top: '0px',
            transform: 'translateX(-50%)',
            marginTop:'-2px'
        },
    },
    root_top:{
        position:'absolute',
        bottom:'100%',
        left:'50%',
        transform:'translateX(-50%)',
        marginBottom:'-1px',
        "&:before" :{
            content: `''`,
            width: '12px',
            height: '30px',
            borderStyle: 'solid',
            borderWidth: '15px 6px 15px 6px',
            boxSizing: 'border-box',
            borderColor: 'transparent transparent #000 transparent',
            position: 'absolute',
            left: '50%',
            bottom: '100%',
            transform: 'translateX(-50%)',
        },
        "&:after" :{
            content: `''`,
            width: '12px',
            height: '30px',
            borderStyle: 'solid',
            borderWidth: '15px 6px 15px 6px',
            boxSizing: 'border-box',
            borderColor: 'transparent transparent #fff transparent',
            position: 'absolute',
            left: '50%',
            bottom: '100%',
            transform: 'translateX(-50%)',
            marginBottom:'-2px'
        },
    },
    root_right:{
        position:'absolute',
        width:'30px',
        height:'12px',
        left:'100%',
        top:'50%',
        transform:'translateY(-50%)',
        marginLeft:'-1px',
        "&:before" :{
            content: `''`,
            width: '100%',
            height: '100%',
            borderStyle: 'solid',
            borderWidth: '6px 15px 6px 15px',
            boxSizing: 'border-box',
            borderColor: 'transparent transparent transparent #000',
            position: 'absolute',
            left: 0,
            top: '50%',
            transform: 'translateY(-50%)',
        },
        "&:after" :{
            content: `''`,
            width: '100%',
            height: '100%',
            borderStyle: 'solid',
            borderWidth: '6px 15px 6px 15px',
            boxSizing: 'border-box',
            borderColor: 'transparent transparent transparent #fff',
            position: 'absolute',
            left: 0,
            top: '50%',
            transform: 'translateY(-50%)',
            marginLeft:'-2px',
        },
    },
    root_left:{
        position:'absolute',
        width:'30px',
        height:'12px',
        right:'100%',
        top:'50%',
        transform:'translateY(-50%)',
        marginRight:'-1px',
        "&:before" :{
            content: `''`,
            width: '100%',
            height: '100%',
            borderStyle: 'solid',
            borderWidth: '6px 15px 6px 15px',
            boxSizing: 'border-box',
            borderColor: 'transparent #000 transparent transparent ',
            position: 'absolute',
            right: 0,
            top: '50%',
            transform: 'translateY(-50%)',
        },
        "&:after" :{
            content: `''`,
            width: '100%',
            height: '100%',
            borderStyle: 'solid',
            borderWidth: '6px 15px 6px 15px',
            boxSizing: 'border-box',
            borderColor: 'transparent #fff transparent transparent',
            position: 'absolute',
            right: 0,
            top: '50%',
            transform: 'translateY(-50%)',
            marginRight:'-2px',
        },
    },
})